--- 
Butter 1: "#fce94f"
Butter 2: "#edd400"
Butter 3: "#c4a000"
Chameleon 1: "#8ae234"
Chameleon 2: "#73d216"
Chameleon 3: "#4e9a06"
Orange 1: "#fcaf3e"
Orange 2: "#f57900"
Orange 3: "#ce5c00"
Sky Blue 1: "#729fcf"
Sky Blue 2: "#3465a4"
Sky Blue 3: "#204a87"
Plum 1: "#ad7fa8"
Plum 2: "#5c3566"
Plum 3: "#5c3566"
Chocolate 1: "#e9b96e"
Chocolate 2: "#c17d11"
Chocolate 3: "#8f5902"
Scarlet Red 1: "#ef2929"
Scarlet Red 2: "#cc0000"
Scarlet Red 3: "#a40000"
Aluminium 1: "#eeeeec"
Aluminium 2: "#d3d7cf"
Aluminium 3: "#babdb6"
Aluminium 4: "#888a85"
Aluminium 5: "#555753"
Aluminium 6: "#2e3436"
