--- 
profiles: 
  cpu+load: 
    plugins: 
      - cpu-0
      - cpu-1
      - load/load
    name: CPU + Load
    order: 1
  memory: 
    plugins: 
      - memory
      - swap
    name: Memory
    order: 2
  disk+usage: 
    plugins: 
      - df/df-root
      - disk-sda
    name: Disk Usage
    order: 3
  network: 
    plugins: 
      - tcpconns-9393-local
      - tcpconns-80-local
    name: Networking
    order: 4
  processes: 
    plugins: 
      - processes
    name: Processes
    order: 5
plugin_colors: 
  memory: 
    memory-used: 
      value: "#cc0000"
    memory-buffered: 
      value: "#edd400"
    memory-cached: 
      value: "#3465a4"
    memory-free: 
      value: "#73d216"
  cpu: 
    cpu-idle: 
      value: "#eeeeec"
    cpu-wait: 
      value: "#edd400"
    cpu-user: 
      value: "#3465a4"
    cpu-system: 
      value: "#cc0000"
    cpu-nice:
      value: "#73d216"
    cpu-softirq: 
      value: "#ad7fa8"
    cpu-interrupt:
      value: "#5c3566"
    cpu-steal:
      value: "#2e3436"
  swap: 
    swap-used: 
      value: "#cc0000"
    swap-free: 
      value: "#73d216"
    swap-cached: 
      value: "#3465a4"
  load: 
    load: 
      longterm: "#ef2929"
      shortterm: "#73d216"
      midterm: "#3465a4"
  df:
    df: 
      used: "#cc0000"
      free: "#73d216"
  disk:
    disk_merged:
       read: "#73d216"
       write: "#cc0000"
    disk_time:
       read: "#73d216"
       write: "#cc0000"
    disk_ops:
       read: "#73d216"
       write: "#cc0000"
    disk_octets:
       read: "#73d216"
       write: "#cc0000"






