---
profiles:
  CPU + Load:
    plugins:
      - cpu-0/cpu-user/cpu-system/cpu-idle/cpu-wait/cpu-interrupt
      - cpu-1
      - load/load
      - battery-0
    splatpart: cpu+load
    order: 1
  Memory:
    plugins:
      - memory
      - swap
    splatpart: mem
    order: 2
  Disk Usage:
    plugins:
      - df/df-root
      - disk-sda
    splatpart: du
    order: 3
  Networking:
    plugins:
      - tcpconns-9393-local
      - tcpconns-80-local
    splatpart: network
    order: 4
  Processes:
    plugins:
      - processes
      - processes-collectd
    splatpart: processes
    order: 5
